---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-{{ .Release.Namespace }}-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.clusterName }}-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin-{{ .Release.Namespace }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.clusterName }}-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-{{ .Release.Namespace }}-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: "{{ .Values.clusterName }}-{{ .Release.Namespace }}"
type: kubernetes.io/service-account-token
