---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.clusterName }}-admin
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.clusterName }}-admin
  namespace: {{ .Release.Namespace }}