---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
#  - apiGroups: ["apps"]
#    resources: ["*"]
#    verbs: ["*"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
#  name: default
  name: jenkins-stage
  namespace: stage

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins
  namespace: stage # только для RoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins
subjects:
- kind: ServiceAccount
#  name: default
  name: jenkins-stage
  namespace: stage

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-stage-token
  namespace: stage
  annotations:
#    kubernetes.io/service-account.name: "default"
    kubernetes.io/service-account.name: "jenkins-stage"
type: kubernetes.io/service-account-token
